/*CREATE DATABASE MAPA_UNIVERSIDADE;
USE MAPA_UNIVERSIDADE;

CREATE TABLE EMPRESA(
EMPRESA_ID INT PRIMARY KEY AUTO_INCREMENT,
NOME_EMPRESA VARCHAR(200) NOT NULL,
CNPJ VARCHAR(100) NOT NULL,
TELEFONE VARCHAR(20) NOT NULL,
EMAIL VARCHAR(200) NOT NULL,
SENHA VARCHAR(20) NOT NULL,
INICIO_CONTRATO DATE NOT NULL,
DATA_RENOVACAO DATE,
TEMPO_CONTRATO_MESES INT NOT NULL,
VALOR_CONTRATO DECIMAL NOT NULL,
REDE_SOCIAL_1 VARCHAR(200),
REDE_SOCIAL_2 VARCHAR(200)
);

/* 
MODERADOR(DESENVOLVEDORES, CADASTRAM EMPRESAS, CRIAM TEMPLATES),
 ADMINISTRADOR(PROPRIA EMPRESA, CADASTRAM USUÁRIOS, ALTERAM AS CORES), 
 GERENTE(CADASTRAM CAMPUS, BLOCOS, PAVIMENTOS, SALAS, PERIODOS, HORARIOS, CURSOS, DISCIPLINAS, QUADROS E USUARIOS DE FUNCOES ABAIXO),
 USUARIO BASICO (SÓ EDITAM PERFIL, CRIAM ANUNCIOS),
 VISITANTE(NÃO PRECISA DE CADASTRO)
 */
CREATE TABLE FUNCOES(
FUNCAO_ID INT PRIMARY KEY AUTO_INCREMENT,
NOME_FUNCAO VARCHAR(100)
);

CREATE TABLE CARGOS(
CARGO_ID INT PRIMARY KEY AUTO_INCREMENT,
NOME_CARGO VARCHAR(100),
EMPRESA_ID int not null,
FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESAS(EMPRESA_ID)
);

CREATE TABLE USUARIOS(
USUARIO_ID INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(200) NOT NULL,
SOBRENOME VARCHAR(200),
NASCIMENTO DATE,
CPF VARCHAR(14) NOT NULL,
MATRICULA INT NOT NULL,
EMAIL VARCHAR(200) NOT NULL,
TELEFONE VARCHAR(20),
SENHA VARCHAR(30) NOT NULL,
FOTO VARCHAR(500),
INFORMACOES_PUBLICAS boolean NOT NULL,
EMPRESA_ID INT NOT NULL,
FUNCAO_ID INT NOT NULL,
CARGO_ID INT NOT NULL,
FOREIGN KEY (FUNCAO_ID) REFERENCES FUNCOES(FUNCAO_ID)
FOREIGN KEY (CARGO_ID) REFERENCES CARGOS(CARGO_ID)
FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESAS(EMPRESA_ID)
);

CREATE TABLE USUARIO_VIP(
VIP_ID INT AUTO_INCREMENT PRIMARY KEY,
USUARIO_ID INT NOT NULL,
INICIO_CONTRATO DATE NOT NULL,
DURACAO_CONTRATO INT NOT NULL,
VALOR_CONTRATO DECIMAL NOT NULL,
ANUNCIOS_CONTRATADOS INT NOT NULL,
FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(USUARIO_ID)
);

CREATE TABLE ANUNCIOS(
ANUNCIO_ID INT AUTO_INCREMENT PRIMARY KEY,
USUARIO_ID INT NOT NULL,
PRODUTO VARCHAR(200) NOT NULL,
DESCRICAO VARCHAR(500),
DATA_INICIO DATE,
DATA_TERMINO DATE NOT NULL,
VALOR DECIMAL,
FOTOS VARCHAR(500),
FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(USUARIO_ID)
);


/*CRIAR TABELA ANUNCIO
ANUNCIO_ID
USUARIO_ID
GERENTES FAZEM ANUNCIO PARA A EMPRESA E USUARIOS BASICOS FAZEM ANUNCIOS PESSOAIS
PRODUTO/SERVICO
DESCRICAO
DATA INICIO AUTOMATICA QUANDO CRIAR ANUNCIO
DATA FIM SELECIONADA PELO USUARIO
VALOR
FOTOS
*/


CREATE TABLE PERIODO(
PERIODO_ID INT PRIMARY KEY auto_increment,
ANO YEAR NOT NULL,
SEMESTRE INT NOT NULL
);

SHOW TABLES;

CREATE TABLE HORARIOS(
HORARIO_ID INT PRIMARY KEY AUTO_INCREMENT,
HORA_INICIO TIME NOT NULL,
HORA_TERMINO TIME NOT NULL,
PERIODO_ID INT,
FOREIGN KEY (PERIODO_ID) REFERENCES PERIODO(PERIODO_ID)
);


CREATE TABLE CAMPI(
CAMPUS_ID INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(200) NOT NULL,
LOGRADOURO VARCHAR(200) NOT NULL,
COMPLEMENTO VARCHAR(100) NOT NULL,
CEP INT,
CIDADE VARCHAR(200) NOT NULL,
ESTADO VARCHAR(200) NOT NULL,
LATITUDE VARCHAR(100) NOT NULL,
LONGITUDE VARCHAR(100) NOT NULL,
EMPRESA_ID INT NOT NULL,
FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESAS(EMPRESA_ID)
);

CREATE TABLE BLOCOS(
BLOCO_ID INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
CAMPUS_ID inT,
FOREIGN KEY (CAMPUS_ID) REFERENCES CAMPI(CAMPUS_ID));

CREATE TABLE PAVIMENTOS(
    PAVIMENTO_ID INT PRIMARY KEY AUTO_INCREMENT,
    NUMERO INT NOT NULL,
    BLOCO_ID INT,
    IMAGEM VARCHAR(500) NOT NULL,
    FOREIGN KEY (BLOCO_ID) REFERENCES BLOCOS(BLOCO_ID)
);

CREATE TABLE TIPOS_AREAS(
TIPO_AREA_ID INT AUTO_INCREMENT PRIMARY KEY,
TIPO VARCHAR(200)
);

CREATE TABLE SALAS(
SALA_ID INT AUTO_INCREMENT PRIMARY KEY,
NUMERO INT NOT NULL,
APELIDO VARCHAR(200) NOT NULL,
TIPO_AREA_ID INT NOT NULL,
PAVIMENTO_ID INT NOT NULL,
IMAGEM VARCHAR(500) NOT NULL,
LISTA_COORDENADAS VARCHAR(500) NOT NULL,
FOREIGN KEY (PAVIMENTO_ID) REFERENCES PAVIMENTO(PAVIMENTO_ID),
FOREIGN KEY (TIPO_AREA_ID) REFERENCES TIPOS_AREAS(TIPO_AREA_ID)
);


CREATE TABLE CURSOS(
CURSO_ID INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(300) NOT NULL
);

CREATE TABLE DISCIPLINAS(
DISCIPLINA_ID INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(200) NOT NULL
);

CREATE TABLE QUADRO_DE_AULAS(
QUADRO_ID INT AUTO_INCREMENT PRIMARY KEY,
PERIODO_ID INT,
DIA_SEMANA INT,
HORA_ID_INICIO INT,
HORA_ID_TERMINO INT,
SALA_ID INT,
CURSO_ID INT,
PROFESSOR INT,
DISCIPLINA_ID INT,
foreign key (DISCIPLINA_ID) REFERENCES DISCIPLINAS(DISCIPLINA_ID),
foreign key (CURSO_ID) REFERENCES CURSOS(CURSO_ID),
foreign key (PERIODO_ID) REFERENCES PERIODO(PERIODO_ID),
foreign key (PROFESSOR) REFERENCES PROFESSORES(USUARIO_ID),
foreign key (HORA_ID_INICIO) REFERENCES HORARIOS(HORARIO_ID),
foreign key (HORA_ID_TERMINO) REFERENCES HORARIOS(HORARIO_ID),
FOREIGN KEY (SALA_ID) REFERENCES SALAS(SALA_ID)
);
SHOW TABLES;




-- NOME DA TABELA -> QUEM PODE EDITAR

-- FUNCOES -> MAPA - OK
CREATE TABLE funcoes (
    funcao_id SERIAL PRIMARY KEY,
    nome VARCHAR(100) UNIQUE NOT NULL
);
--MODELOS -> MAPA - CRIADO - OK
create table modelos(
    modelo_id serial primary key,
    nome varchar(100) not null,
    imoveis varchar(50) not null,
    comodos varchar(50) not null,
    categorias varchar(50) not null,
    produtos varchar(50) not null,
)
-- Empresas -> MAPA - OK

CREATE TABLE empresas (
    empresa_id uuid primary key default uuid_generate_v4(),
    user_id uuid references auth.users(id) on delete cascade,
    data_cadastro timestamp default now(),
    nome VARCHAR(200) NOT NULL,
    cnpj VARCHAR(100) unique NOT NULL,
    telefone VARCHAR(20) NOT NULL,
    email VARCHAR(200) unique NOT NULL,
    senha VARCHAR(20) NOT NULL,
    rede_social_1 VARCHAR(200),
    rede_social_2 VARCHAR(200),
    imagem VARCHAR(500),
    visibilidade BOOLEAN NOT NULL,
    modelo_id references modelos(modelo_id),
    validacao boolean default false
);

-- como gerente da empresa quero definir os cargos dos meus funcionários cadastrados no site ex. professores, coordenadores, secretários, auxiliares, alunos, porteiros
-- Cargos -> EMPRESA - OK
CREATE TABLE cargos (
    cargo_id SERIAL PRIMARY KEY,
    nome VARCHAR(100) unique,
    empresa_id INT NOT NULL REFERENCES empresas(empresa_id)
);
-- CONTRATOS -> MAPA - ok

CREATE TABLE contratos_empresas(
    contrato_id SERIAL PRIMAY KEY;
    inicio DATE NOT NULL,
    renovacao DATE,
    tempo_contrato_meses INT NOT NULL,
    valor DECIMAL(10,2) NOT NULL,
    empresa_id unique INT NOT NULL REFERENCES empresas(empresa_id),
    qtd_comodos int not null,
    qtd_produtos int not null,
    qtd_usuários int not null,
    data_cadastro timestamp default now(),
    validacao boolean default false
)
-- Usuários -> EMPRESA, COORDENADOR
-- EMPRESA CRIA USUARIOS DE QUALQUER CARGO, COORDENADOR CRIA PROFESSORES PARA O CURSO DELE
CREATE TABLE usuarios (
    usuario_id uuid primary key default uuid_generate_v4(),
    user_id uuid references auth.users(id) on delete cascade,
    data_cadastro timestamp default now(),
    nome VARCHAR(200) NOT NULL,
    sobrenome VARCHAR(200),
    nascimento DATE,
    cpf VARCHAR(14) unique NOT NULL,
    telefone VARCHAR(20),
    email VARCHAR(200) unique NOT NULL,
    senha VARCHAR(30) NOT NULL,
    pin int4 not null,
    rede_social VARCHAR(200) unique NOT NULL,
    imagem VARCHAR(500),
    visibilidade BOOLEAN set default true,
    validacao boolean default false
);
--USUARIOS CADASTRADOS NA EMPRESA (ESSE FORMATO PERMITE MUITOS USUARIOS PARA MUITAS EMPRESAS) -> EMPRESA, COORDENADOR
create table usuarios_empresas(
    id serial primary key,
    matricula INT NOT NULL,
    usuario_id int NOT NULL references usuarios(usuario_id),
    empresa_id int NOT NULL references empresas(empresa_id),
    funcao_id INT NOT NULL REFERENCES funcoes(funcao_id),
    cargo_id INT NOT NULL REFERENCES cargos(cargo_id),
    validacao boolean default false,
    data_cadastro timestamp default now(),
);

-- Horários -> EMPRESA
CREATE TABLE horarios (
    horario_id SERIAL PRIMARY KEY,
    ano INT4 NOT NULL,
    semestre INT2 NOT NULL
    hora_inicio TIME NOT NULL,
    hora_termino TIME NOT NULL,
);

-- Tipos de Áreas -> MAPA
CREATE TABLE tipos_areas (
    tipo_area_id SERIAL PRIMARY KEY,
    nome VARCHAR(200)
);
-- Campi -> EMPRESA
CREATE TABLE imoveis (
    imovel_id SERIAL PRIMARY KEY,
    nome VARCHAR(200) NOT NULL,
    logradouro VARCHAR(200) NOT NULL,
    complemento VARCHAR(100) NOT NULL,
    cep VARCHAR(20),
    cidade VARCHAR(200) NOT NULL,
    estado VARCHAR(200) NOT NULL,
    latitude VARCHAR(100),
    longitude VARCHAR(100),
    empresa_id INT NOT NULL REFERENCES empresas(empresa_id)
);

-- Blocos -> EMPRESA
CREATE TABLE blocos (
    bloco_id SERIAL PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    imovel_id INT REFERENCES imoveis(imovel_id)
);

-- Pavimentos -> EMPRESA
CREATE TABLE pavimentos (
    pavimento_id SERIAL PRIMARY KEY,
    numero INT NOT NULL,
    bloco_id INT REFERENCES blocos(bloco_id),
    imagem VARCHAR(500) NOT NULL
);


-- Salas -> EMPRESA
CREATE TABLE comodos (
    comodo_id SERIAL PRIMARY KEY,
    numero INT NOT NULL,
    apelido VARCHAR(200) NOT NULL,
    tipo_area_id INT NOT NULL REFERENCES tipos_areas(tipo_area_id),
    pavimento_id INT NOT NULL REFERENCES pavimentos(pavimento_id),
    lotacao int not null,
    lista_coordenadas VARCHAR(500) NOT NULL
);

-- Cursos -> EMPRESA
CREATE TABLE categorias (
    categoria_id SERIAL PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    descricao varchar(500)
);

-- Disciplinas -> EMPRESA, COORDENADOR, SECRETARIO
CREATE TABLE produtos (
    produtos_id SERIAL PRIMARY KEY,
    nome VARCHAR(200) NOT NULL,
    descricao varchar(500),
    valor float,
    foto VARCHAR(500)
);

-- Quadro de Aulas -> EMPRESA, COORDENADOR, SECRETARIO
-- QUADRO DE FUNCIONAMENTO PASSARÁ PARA NOSQL E DEVE PERMITIR ADICIONAR MULTIPLOS PRODUTOS, USUÁRIOS E CATEGORIAS
-- retirar 10 segundos do tempo de termino para evitar conflitos
CREATE TABLE quadro_de_funcionamento (
    quadro_id SERIAL PRIMARY KEY,
    qtd_lotacao int,
    dia_semana INT,
    hora_id_inicio INT REFERENCES horarios(horario_id),
    hora_id_termino INT REFERENCES horarios(horario_id),
    comodo_id INT REFERENCES comodos(comodo_id),
    categoria_id INT REFERENCES categorias(categoria_id),
    usuario_id INT REFERENCES usuarios(usuario_id),
    produto_id INT REFERENCES produtos(produto_id)
);


*/