CREATE DATABASE MAPA_UNIVERSIDADE;
USE MAPA_UNIVERSIDADE;

CREATE TABLE EMPRESA(
EMPRESA_ID INT PRIMARY KEY AUTO_INCREMENT,
NOME_EMPRESA VARCHAR(200) NOT NULL,
CNPJ VARCHAR(100) NOT NULL,
TELEFONE VARCHAR(20) NOT NULL,
EMAIL VARCHAR(200) NOT NULL,
SENHA VARCHAR(20) NOT NULL,
INICIO_CONTRATO DATE NOT NULL,
DATA_RENOVACAO DATE,
TEMPO_CONTRATO_MESES INT NOT NULL,
VALOR_CONTRATO DECIMAL NOT NULL,
REDE_SOCIAL_1 VARCHAR(200),
REDE_SOCIAL_2 VARCHAR(200)
);

/* 
MODERADOR(DESENVOLVEDORES, CADASTRAM EMPRESAS, CRIAM TEMPLATES),
 ADMINISTRADOR(PROPRIA EMPRESA, CADASTRAM USUÁRIOS, ALTERAM AS CORES), 
 GERENTE(CADASTRAM CAMPUS, BLOCOS, PAVIMENTOS, SALAS, PERIODOS, HORARIOS, CURSOS, DISCIPLINAS, QUADROS E USUARIOS DE FUNCOES ABAIXO),
 USUARIO BASICO (SÓ EDITAM PERFIL, CRIAM ANUNCIOS),
 VISITANTE(NÃO PRECISA DE CADASTRO)
 */
CREATE TABLE FUNCOES(
FUNCAO_ID INT PRIMARY KEY AUTO_INCREMENT,
NOME_FUNCAO VARCHAR(100)
);

CREATE TABLE CARGOS(
CARGO_ID INT PRIMARY KEY AUTO_INCREMENT,
NOME_CARGO VARCHAR(100)
);

CREATE TABLE USUARIOS(
USUARIO_ID INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(200) NOT NULL,
SOBRENOME VARCHAR(200) NOT NULL,
NASCIMENTO VARCHAR(10) NOT NULL,
CPF VARCHAR(14) NOT NULL,
MATRICULA INT NOT NULL,
EMAIL VARCHAR(200) NOT NULL,
TELEFONE VARCHAR(20),
SENHA VARCHAR(30) NOT NULL,
FOTO VARCHAR(500),
EMPRESA_ID INT NOT NULL,
INFORMACOES_PUBLICAS boolean NOT NULL,
FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESAS(EMPRESA_ID)
);

CREATE TABLE USUARIO_VIP(
VIP_ID INT AUTO_INCREMENT PRIMARY KEY,
USUARIO_ID INT NOT NULL,
INICIO_CONTRATO DATE NOT NULL,
DURACAO_CONTRATO INT NOT NULL,
VALOR_CONTRATO DECIMAL NOT NULL,
ANUNCIOS_CONTRATADOS INT NOT NULL,
FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(USUARIO_ID)
);

CREATE TABLE ANUNCIOS(
ANUNCIO_ID INT AUTO_INCREMENT PRIMARY KEY,
USUARIO_ID INT NOT NULL,
PRODUTO VARCHAR(200) NOT NULL,
DESCRICAO VARCHAR(500),
DATA_INICIO DATE,
DATA_TERMINO DATE NOT NULL,
VALOR DECIMAL,
FOTOS VARCHAR(500),
FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(USUARIO_ID)
);


/*CRIAR TABELA ANUNCIO
ANUNCIO_ID
USUARIO_ID
GERENTES FAZEM ANUNCIO PARA A EMPRESA E USUARIOS BASICOS FAZEM ANUNCIOS PESSOAIS
PRODUTO/SERVICO
DESCRICAO
DATA INICIO AUTOMATICA QUANDO CRIAR ANUNCIO
DATA FIM SELECIONADA PELO USUARIO
VALOR
FOTOS
*/


CREATE TABLE PERIODO(
PERIODO_ID INT PRIMARY KEY auto_increment,
ANO YEAR NOT NULL,
SEMESTRE INT NOT NULL
);

SHOW TABLES;

CREATE TABLE HORARIOS(
HORARIO_ID INT PRIMARY KEY AUTO_INCREMENT,
HORA_INICIO TIME NOT NULL,
HORA_TERMINO TIME NOT NULL,
PERIODO_ID INT,
FOREIGN KEY (PERIODO_ID) REFERENCES PERIODO(PERIODO_ID)
);


CREATE TABLE CAMPI(
CAMPUS_ID INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(200) NOT NULL,
LOGRADOURO VARCHAR(200) NOT NULL,
COMPLEMENTO VARCHAR(100) NOT NULL,
CEP INT,
CIDADE VARCHAR(200) NOT NULL,
ESTADO VARCHAR(200) NOT NULL,
LATITUDE VARCHAR(100) NOT NULL,
LONGITUDE VARCHAR(100) NOT NULL
);

CREATE TABLE BLOCOS(
BLOCO_ID INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
CAMPUS_ID inT,
FOREIGN KEY (CAMPUS_ID) REFERENCES CAMPI(CAMPUS_ID));

CREATE TABLE PAVIMENTOS(
    PAVIMENTO_ID INT PRIMARY KEY AUTO_INCREMENT,
    NUMERO INT NOT NULL,
    BLOCO_ID INT,
    IMAGEM VARCHAR(500) NOT NULL,
    FOREIGN KEY (BLOCO_ID) REFERENCES BLOCOS(BLOCO_ID)
);

CREATE TABLE TIPOS_AREAS(
TIPO_AREA_ID INT AUTO_INCREMENT PRIMARY KEY,
TIPO VARCHAR(200)
);

CREATE TABLE SALAS(
SALA_ID INT AUTO_INCREMENT PRIMARY KEY,
NUMERO INT NOT NULL,
APELIDO VARCHAR(200) NOT NULL,
TIPO_AREA_ID INT NOT NULL,
PAVIMENTO_ID INT NOT NULL,
IMAGEM VARCHAR(500) NOT NULL,
LISTA_COORDENADAS VARCHAR(500) NOT NULL,
FOREIGN KEY (PAVIMENTO_ID) REFERENCES PAVIMENTO(PAVIMENTO_ID),
FOREIGN KEY (TIPO_AREA_ID) REFERENCES TIPOS_AREAS(TIPO_AREA_ID)
);


CREATE TABLE CURSOS(
CURSO_ID INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(300) NOT NULL
);

CREATE TABLE DISCIPLINAS(
DISCIPLINA_ID INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(200) NOT NULL
);

CREATE TABLE QUADRO_DE_AULAS(
QUADRO_ID INT AUTO_INCREMENT PRIMARY KEY,
PERIODO_ID INT,
DIA_SEMANA INT,
HORA_ID_INICIO INT,
HORA_ID_TERMINO INT,
SALA_ID INT,
CURSO_ID INT,
PROFESSOR INT,
DISCIPLINA_ID INT,
foreign key (DISCIPLINA_ID) REFERENCES DISCIPLINAS(DISCIPLINA_ID),
foreign key (CURSO_ID) REFERENCES CURSOS(CURSO_ID),
foreign key (PERIODO_ID) REFERENCES PERIODO(PERIODO_ID),
foreign key (PROFESSOR) REFERENCES PROFESSORES(USUARIO_ID),
foreign key (HORA_ID_INICIO) REFERENCES HORARIOS(HORARIO_ID),
foreign key (HORA_ID_TERMINO) REFERENCES HORARIOS(HORARIO_ID),
FOREIGN KEY (SALA_ID) REFERENCES SALAS(SALA_ID)
);
SHOW TABLES;